DROP TABLE IF EXISTS `USUARIOS`;

CREATE TABLE `USUARIOS` (
    `EMAIL` VARCHAR(50) NOT NULL,
    `NOMBRE` VARCHAR(20) NOT NULL,
    `APELLIDO` VARCHAR(20) NOT NULL,
    `TELEFONO` VARCHAR(15) NOT NULL,
    `GRADOS` VARCHAR(50) NOT NULL,
    `CLAVE` VARCHAR(255) NOT NULL, 
    PRIMARY KEY (`EMAIL`)
);

